#!/usr/bin/env python
# -*- coding: utf-8 -*-

from typing import Dict, List

###############################################################################

# The order of the readers in this impl dict is important.
#
# Example:
# if TiffReader was placed before OmeTiffReader,
# we would never hit the OmeTiffReader

# Additionally while so many formats can be read by base-imageio
# Our custom reader may be more well-suited for interactions
# Example:
# DefaultReader supports LSM, and all the similar "Tiff-Like"
# formats, but TiffReader does as well and it has better
# dask chunking + metadata parsing than DefaultReader for those formats

# BASE-IMAGEIO FORMATS (with tifffile + non-existant removals)
#
# Pulled using:
# from imageio import formats
# routes = {}
# for f in formats:
#   for ext in f.extensions:
#       routes[ext[1:]] = ["aicsimageio.readers.default_reader.DefaultReader"]

FORMAT_IMPLEMENTATIONS: Dict[str, List[str]] = {
    "array-like": ["aicsimageio.readers.array_like_reader.ArrayLikeReader"],
    "ome.tiff": [
        "aicsimageio.readers.ome_tiff_reader.OmeTiffReader",
        "aicsimageio.readers.tiff_reader.TiffReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "ome.tif": [
        "aicsimageio.readers.ome_tiff_reader.OmeTiffReader",
        "aicsimageio.readers.tiff_reader.TiffReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "tiff": [
        "aicsimageio.readers.ome_tiff_reader.OmeTiffReader",
        "aicsimageio.readers.tiff_reader.TiffReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "tif": [
        "aicsimageio.readers.ome_tiff_reader.OmeTiffReader",
        "aicsimageio.readers.tiff_reader.TiffReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "czi": [
        "aicsimageio.readers.czi_reader.CziReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "lif": [
        "aicsimageio.readers.lif_reader.LifReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "bmp": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "bufr": ["aicsimageio.readers.default_reader.DefaultReader"],
    "cur": ["aicsimageio.readers.default_reader.DefaultReader"],
    "dcx": ["aicsimageio.readers.default_reader.DefaultReader"],
    "dds": ["aicsimageio.readers.default_reader.DefaultReader"],
    "ps": ["aicsimageio.readers.default_reader.DefaultReader"],
    "eps": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "fit": ["aicsimageio.readers.default_reader.DefaultReader"],
    "fits": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "fli": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "flc": ["aicsimageio.readers.default_reader.DefaultReader"],
    "fpx": ["aicsimageio.readers.default_reader.DefaultReader"],
    "ftc": ["aicsimageio.readers.default_reader.DefaultReader"],
    "ftu": ["aicsimageio.readers.default_reader.DefaultReader"],
    "gbr": ["aicsimageio.readers.default_reader.DefaultReader"],
    "gif": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "grib": ["aicsimageio.readers.default_reader.DefaultReader"],
    "h5": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "hdf": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "icns": ["aicsimageio.readers.default_reader.DefaultReader"],
    "ico": ["aicsimageio.readers.default_reader.DefaultReader"],
    "im": ["aicsimageio.readers.default_reader.DefaultReader"],
    "iim": ["aicsimageio.readers.default_reader.DefaultReader"],
    "jfif": ["aicsimageio.readers.default_reader.DefaultReader"],
    "jpe": ["aicsimageio.readers.default_reader.DefaultReader"],
    "jpg": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "jpeg": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "jp2": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "j2k": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "jpc": ["aicsimageio.readers.default_reader.DefaultReader"],
    "jpf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "jpx": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "j2c": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mic": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mpo": ["aicsimageio.readers.default_reader.DefaultReader"],
    "msp": ["aicsimageio.readers.default_reader.DefaultReader"],
    "pcd": ["aicsimageio.readers.default_reader.DefaultReader"],
    "pcx": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "pxr": ["aicsimageio.readers.default_reader.DefaultReader"],
    "png": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "pbm": ["aicsimageio.readers.default_reader.DefaultReader"],
    "pgm": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "ppm": ["aicsimageio.readers.default_reader.DefaultReader"],
    "psd": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "bw": ["aicsimageio.readers.default_reader.DefaultReader"],
    "rgb": ["aicsimageio.readers.default_reader.DefaultReader"],
    "rgba": ["aicsimageio.readers.default_reader.DefaultReader"],
    "ras": ["aicsimageio.readers.default_reader.DefaultReader"],
    "tga": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "wmf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "emf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "xbm": ["aicsimageio.readers.default_reader.DefaultReader"],
    "xpm": ["aicsimageio.readers.default_reader.DefaultReader"],
    "cut": ["aicsimageio.readers.default_reader.DefaultReader"],
    "exr": ["aicsimageio.readers.default_reader.DefaultReader"],
    "g3": ["aicsimageio.readers.default_reader.DefaultReader"],
    "hdr": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "iff": ["aicsimageio.readers.default_reader.DefaultReader"],
    "lbm": ["aicsimageio.readers.default_reader.DefaultReader"],
    "jng": ["aicsimageio.readers.default_reader.DefaultReader"],
    "jif": ["aicsimageio.readers.default_reader.DefaultReader"],
    "jxr": ["aicsimageio.readers.default_reader.DefaultReader"],
    "wdp": ["aicsimageio.readers.default_reader.DefaultReader"],
    "hdp": ["aicsimageio.readers.default_reader.DefaultReader"],
    "koa": ["aicsimageio.readers.default_reader.DefaultReader"],
    "pfm": ["aicsimageio.readers.default_reader.DefaultReader"],
    "pct": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "pict": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "pic": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "3fr": ["aicsimageio.readers.default_reader.DefaultReader"],
    "arw": ["aicsimageio.readers.default_reader.DefaultReader"],
    "bay": ["aicsimageio.readers.default_reader.DefaultReader"],
    "bmq": ["aicsimageio.readers.default_reader.DefaultReader"],
    "cap": ["aicsimageio.readers.default_reader.DefaultReader"],
    "cine": ["aicsimageio.readers.default_reader.DefaultReader"],
    "cr2": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "crw": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "cs1": ["aicsimageio.readers.default_reader.DefaultReader"],
    "dc2": ["aicsimageio.readers.default_reader.DefaultReader"],
    "dcr": ["aicsimageio.readers.default_reader.DefaultReader"],
    "drf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "dsc": ["aicsimageio.readers.default_reader.DefaultReader"],
    "dng": ["aicsimageio.readers.default_reader.DefaultReader"],
    "erf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "fff": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "ia": ["aicsimageio.readers.default_reader.DefaultReader"],
    "iiq": ["aicsimageio.readers.default_reader.DefaultReader"],
    "k25": ["aicsimageio.readers.default_reader.DefaultReader"],
    "kc2": ["aicsimageio.readers.default_reader.DefaultReader"],
    "kdc": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mdc": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mef": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mos": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mrw": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "nef": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "nrw": ["aicsimageio.readers.default_reader.DefaultReader"],
    "orf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "pef": ["aicsimageio.readers.default_reader.DefaultReader"],
    "ptx": ["aicsimageio.readers.default_reader.DefaultReader"],
    "pxn": ["aicsimageio.readers.default_reader.DefaultReader"],
    "qtk": ["aicsimageio.readers.default_reader.DefaultReader"],
    "raf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "raw": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "rdc": ["aicsimageio.readers.default_reader.DefaultReader"],
    "rw2": ["aicsimageio.readers.default_reader.DefaultReader"],
    "rwl": ["aicsimageio.readers.default_reader.DefaultReader"],
    "rwz": ["aicsimageio.readers.default_reader.DefaultReader"],
    "sr2": ["aicsimageio.readers.default_reader.DefaultReader"],
    "srf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "srw": ["aicsimageio.readers.default_reader.DefaultReader"],
    "sti": ["aicsimageio.readers.default_reader.DefaultReader"],
    "targa": ["aicsimageio.readers.default_reader.DefaultReader"],
    "wap": ["aicsimageio.readers.default_reader.DefaultReader"],
    "wbmp": ["aicsimageio.readers.default_reader.DefaultReader"],
    "wbm": ["aicsimageio.readers.default_reader.DefaultReader"],
    "webp": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mov": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "avi": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "mpg": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mpeg": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mp4": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mkv": ["aicsimageio.readers.default_reader.DefaultReader"],
    "wmv": ["aicsimageio.readers.default_reader.DefaultReader"],
    "bsdf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "dcm": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "ct": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mri": ["aicsimageio.readers.default_reader.DefaultReader"],
    "npz": ["aicsimageio.readers.default_reader.DefaultReader"],
    "swf": ["aicsimageio.readers.default_reader.DefaultReader"],
    "fts": ["aicsimageio.readers.default_reader.DefaultReader"],
    "fz": ["aicsimageio.readers.default_reader.DefaultReader"],
    "gipl": ["aicsimageio.readers.default_reader.DefaultReader"],
    "ipl": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "mha": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mhd": ["aicsimageio.readers.default_reader.DefaultReader"],
    "nhdr": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "nia": ["aicsimageio.readers.default_reader.DefaultReader"],
    "nrrd": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "nii": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "niigz": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "img": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "imggz": ["aicsimageio.readers.default_reader.DefaultReader"],
    "vtk": ["aicsimageio.readers.default_reader.DefaultReader"],
    "hdf5": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mnc": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "mnc2": ["aicsimageio.readers.default_reader.DefaultReader"],
    "mgh": ["aicsimageio.readers.default_reader.DefaultReader"],
    "dicom": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "gdcm": ["aicsimageio.readers.default_reader.DefaultReader"],
    "ecw": ["aicsimageio.readers.default_reader.DefaultReader"],
    "lfr": ["aicsimageio.readers.default_reader.DefaultReader"],
    "lfp": ["aicsimageio.readers.default_reader.DefaultReader"],
    "spe": [
        "aicsimageio.readers.default_reader.DefaultReader",
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
    ],
    "1sc": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "2fl": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "acff": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "acqp": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "afi": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "afm": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "aim": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "al3d": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ali": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "am": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "amiramesh": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ano": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "apl": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "arf": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "bif": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "bin": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "bip": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "c01": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "cat": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "cfg": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ch5": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "cif": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "csv": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ct.img": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "cxd": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "dat": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "db": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "df3": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "dm2": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "dm3": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "dti": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "dv": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "epsi": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "exp": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "fake": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "fdf": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ffr": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "fid": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "flex": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "frm": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "gel": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "grey": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "hed": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "his": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "htd": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "htm": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "html": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "hx": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "i2i": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ics": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ids": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "im3": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ims": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "inf": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "inr": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ipm": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ipw": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "jpk": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "klb": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "l2d": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "labels": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "lei": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "liff": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "lim": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "lms": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "lsm": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "mdb": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "mng": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "mod": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "mrc": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "msr": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "mtb": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "mvd2": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "naf": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "nd": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "nd2": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ndpi": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ndpis": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "nii.gz": [
        "aicsimageio.readers.bioformats_reader.BioformatsReader",
        "aicsimageio.readers.default_reader.DefaultReader",
    ],
    "obf": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "oib": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "oif": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "oir": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "ome": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "par": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "pcoraw": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "pnl": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "pr3": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "qptiff": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "r3d": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "rcpnl": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "rec": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "scan": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "scn": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "sdt": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "seq": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "sif": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "sld": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "sm2": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "sm3": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "spc": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "spi": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "st": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "stk": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "stp": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "svs": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "sxm": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "tfr": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "thm": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "tim": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "tnb": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "top": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "txt": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "v": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "vff": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "vms": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "vsi": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "vws": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "wat": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "wav": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "wlz": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "wpi": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "xdce": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "xml": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "xqd": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "xqf": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "xv": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "xys": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "zfp": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "zfr": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "zip": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "zpo": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
    "zvi": ["aicsimageio.readers.bioformats_reader.BioformatsReader"],
}

READER_TO_INSTALL: Dict[str, str] = {
    "aicsimageio.readers.bioformats_reader.BioformatsReader": "bioformats",
    "aicsimageio.readers.default_reader.DefaultReader": "base-imageio",
    "aicsimageio.readers.lif_reader.LifReader": "lif",
    "aicsimageio.readers.czi_reader.CziReader": "czi",
}
