# Autogenerated file - DO NOT EDIT MANUALLY
MODULE_VERSION = "0.6.4"

# For snapshot, X.Y.Z.devN -> X.Y.Z.devN+1
#    bumpversion devbuild
#
# For release, X.Y.Z.devN -> X.Y.Z
#    bumpversion release
#    DO NOT CALL release on consecutive calls
#    DO NOT CALL release on 0.0.0.devN
#
# For preparing for next development cycle after release
#    bumpversion patch    (X.Y.Z -> X.Y.Z+1.dev0)
#    bumpversion minor    (X.Y.Z -> X.Y+1.Z.dev0)
#    bumpversion major    (X.Y.Z -> X+1.Y.Z.dev0)
#
