# Test the core library against upstream dependencies
# If fail, please report bugs to the appropriate library

name: Test Upstreams

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Mon,Wed,Thurs at 19:00:00 UTC (Monday at 11:00:00 PST)
    - cron: "0 19 * * 1,3,4"

jobs:
  test-core-lib:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']
        os: [
          ubuntu-20.04,
          windows-latest,
          macos-11,
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - uses: actions/cache@v2
        id: cache
        with:
          path: aicsimageio/tests/resources
          key: ${{ hashFiles('scripts/TEST_RESOURCES_HASH.txt') }}
      - name: Download Test Resources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python scripts/download_test_resources.py --debug
      - name: Run tests with Tox
        run: tox -e upstreams